# This is the API of trash
openapi: "3.0.3"
info:
  title: Trash API
  description: Trash Rest API接口
  version: "0.0.1"
servers:
  - url: http://localhost:11273/v0
paths:
  /stocks/simple:
    get:
      summary: stock's symbol and name
      description: 获取所有股票的代码和名称
      tags: 
        - Stocks
      responses:
        '200':
          description: An array of stocks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StockList"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /stocks/detail:
    get:
      summary: stock detail info
      description: 当前时刻股票的信息
      tags:
        - Stocks
      parameters:
      - in: query
        name: id
        schema:
          type: integer
        description: 要获取的合约代码
      responses:
        '200':
          description: An array of stocks
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: number
                    description: 价格
                    example: 12.2
                  volumn:
                    type: integer
                    description: 交易量
                    example: 168
  /stocks/history:
    get:
      summary: stock detail info
      description: 历史股票的信息
      tags:
        - Stocks
      parameters:
      - in: query
        name: id
        schema:
          type: integer
        description: 要获取的合约代码
      - in: query
        name: type
        schema:
          type: integer
        description: 获取的合约类型(时分1/日2/周3/月4)
      - in: query
        name: start
        schema:
          type: integer
        description: 开始时间
      - in: query
        name: end
        schema:
          type: integer
        description: 结束时间
      responses:
        '200':
          description: An array of stocks
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: number
                    description: 价格
                    example: 12.2
  /order/buy:
    post:
      summary: buy a contract
      description: 购买合约
      tags: 
        - Order
      requestBody:
        description: 合约信息
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                  description: 合约代码
                  example: 000001
                count:
                  type: integer
                  description: 份数
                  example: 100
                price:
                  type: array
                  description: 价格
                  items:
                    type: number
                    example: 12.3
      responses:
        '200':
          description: success or not
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StockList"
  /simulate:
    post:
      summary: simulate a exchange
      description: 交易所仿真
      tags: 
        - Simulate
      requestBody:
        description: 交易所信息
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: 交易所类型
                  example: stock
                enable:
                  type: boolean
                  description: 开启或关闭
                  example: true
      responses:
        '200':
          description: success or not
  /risk/stoploss:
    post:
      summary: stoploss
      description: 止损设置
      tags: 
        - Risk
      requestBody:
        description: 止损参数
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: integer
                  description: 止损类型 (0-7)
                  example: 0
                email:
                  type: string
                  description: 止损提示的email地址
                  example: webbery@wo.cn
                target:
                  type: array
                  description: 标的信息
                  items:
                    type: object
                    properties:
                      price:
                        type: number
                        description: 止损提示的初始价格
                        example: 48.41
                      symbol:
                        type: string
                        description: 代码
                        example: 001136
                      type:
                        type: string
                        description: 代码类型
                        example: AStock
                      percent:
                        type: number
                        description: 止损百分比
                        example: 0.05
      responses:
        '200':
          description: success or not
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: 设置成功后返回的id
                    example: 12
    delete:
      summary: stoploss
      description: 删除设置的止损
      tags: 
        - Risk
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          description: 要删除的id
      responses:
        '200':
          description: success
    get:
      summary: stoploss
      description: 获取所有设置的止损
      tags: 
        - Risk
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StopLossList"
  /risk/var:
    post:
      summary: run strategy for VaR
      description: 计算策略的VaR
      tags:
        - Risk
      requestBody:
        description: 计算VaR的参数
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                strategy:
                  type: string
                  description: 策略名
                  example: random
                start:
                  type: string
                  description: 回测开始时间
                  example: "2010-01-01 00:00:00"
                end:
                  type: string
                  description: 回测结束时间
                  example: "2030-01-01 00:00:00"
                portfolio:
                  type: string
                  description: 组合名
                  example: random-1
                confidence:
                  type: number
                  description: 置信度
                  example: 0.99
                days:
                  type: integer
                  description: 预测未来N天
                  example: 10
                commission:
                  type: integer
                  description: 设置的佣金ID
                  example: 3
      responses:
        '200':
          description: success or not
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: var的id
                    example: 1
                  loss:
                    type: number
                    description: 损失
                    example: 100000.0
                  sharp:
                    type: number
                    description: 夏普率
                    example: 1.2
    get:
      summary: get strategy of history VaR
      description: 获取历史计算出的策略的VaR
      tags:
        - Risk
      parameters:
        - in: query
          name: id
          schema:
            type: integer
            description: 佣金id
      responses:
        '200':
          description: success or not
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: var的id
                      example: 1
  /portfolio:
    put:
      summary: portfolio
      description: 创建一个投资组合
      tags: 
        - Portfolio
      requestBody:
        description: 投资组合参数
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                total:
                  type: number
                  description: 总资产
                  example: 100000
                pool:
                  type: array
                  description: 池子
                  items:
                    type: string
                    description: 代码
                    example: "000001"
      responses:
        '200':
          description: success or not
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: 设置成功后返回的id
                    example: 121
  /commission:
    put:
      summary: commission
      description: 创建一个佣金
      tags: 
        - Commission
      requestBody:
        description: 佣金参数
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 给设置取的名称
                min:
                  type: number
                  description: 单比交易最低佣金
                value:
                  type: number
                  description: 单比交易佣金比例
                tax:
                  type: number
                  description: 卖出税费
                type:
                  type: string
                  description: 计算类型
      responses:
        '200':
          description: success or not
          content:
            application/json:
              schema:
                type: integer
                description: 设置成功后返回的id
                example: 121
    get:
      summary: commission
      description: 获取创建的佣金
      tags: 
        - Commission
      parameters:
        - in: query
          name: id
          schema:
            type: integer
            description: 佣金id
            example: 12
      responses:
        '200':
          description: success or not
          content:
            application/json:
              schema:
                type: array
                description: 返回的佣金信息
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: 佣金的id
                      example: 12
                    name:
                      type: string
                      description: 给设置取的名称
                    min:
                      type: number
                      description: 单比交易最低佣金
                    value:
                      type: number
                      description: 单比交易佣金比例
                    tax:
                      type: number
                      description: 卖出税费
                    type:
                      type: string
                      description: 计算类型
    delete:
      summary: commission
      description: 删除佣金
      tags: 
        - Commission
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          description: 要删除的佣金id
      responses:
        '200':
          description: success or not
  /strategy/metric:
    get:
      summary: metric
      description: 获取策略的评价指标
      tags: 
        - Strategy
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          description: 要获取的策略id
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  annual:
                    type: number
                    description: 年化收益率
                    example: 0
                  backward:
                    type: number
                    description: 最大回测
                    example: 0
                  wintimes:
                    type: integer
                    description: 盈利次数
                    example: 0
                  failtimes:
                    type: integer
                    description: 亏损次数
                    example: 0
                  winrate:
                    type: number
                    description: 胜率
                    example: 0
                  plrate:
                    type: number
                    description: 盈亏比
                    example: 0
                  sharp:
                    type: number
                    description: 夏普比率
                    example: 0
                  starttime:
                    type: string
                    description: 策略开始运行的时间
                    example: '2010/01/01 00:00:00'
                  endtime:
                    type: string
                    description: 策略停止的时间
                    example: '2020/01/01 00:00:00'
components:
  schemas:
    StockList:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 0
        status:
          type: string
          description: Order Status
          example: success
          enum:
            - fail
            - success
        stocks:
          type: array
          description: stock list
          items:
            type: object
            properties:
              symbol:
                type: string
                example: '000002'
              name:
                type: string
                example: '中国银行'
      xml:
        name: order
    StopLossList:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 33
        type:
          type: string
          description: 止损类型
          example: 'percentage'
        porfolio:
          type: array
          description: 代码
          items:
            type: object
            properties:
              price:
                type: number
                description: 止损提示的初始价格
                example: 48.41
              symbol:
                type: string
                description: 代码
                example: '001136'
              type:
                type: string
                description: 代码类型
                example: 'Astock'
    Error:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
        msg:
          type: string
          example: error
      xml:
        name: customer